### PR TITLE
Add Pug formatting using Prettier

### PR DESCRIPTION
**Pull request by mondeja**
This has been already added in [simple-icons-font](https://github.com/simple-icons/simple-icons-font) repository.

### CODE REVIEW

**Review by jorgeamadosoria — APPROVED** [review]
cool

**Comment by jorgeamadosoria** [comment]
Please resolve conflicts introduced by the other PRs and merge this when ready.

**Review by jorgeamadosoria — APPROVED** [review]
I personally don't like this style, but I like to have a consistent formatter on all files, so that supersedes personal preference.

**Comment by mondeja** [comment]
I don't really like any style, but I like not having to think about style in any files 😆

**Pull request merged**
