### PR TITLE
Add mangling to reduce website size

### PR DESCRIPTION
**Pull request by ericcornelissen**
Use a custom (*) mangler (that I built for this purpose) to reduce website size. The mangler will look at all the classes (given a base expression) in the HTML, CSS, and JS of the project and, based on how often they appear, replace them by shorter strings. Given that some classes appear over 1500 time (once per brand), this has quite some effect on the size of the website. It will do the same for CSS variables, HTML data attributes and HTML ids; but the gains for these are less.

---

<sup>*: I've looked into using existing ones for Webpack, [e.g. mangle-css-class-webpack-plugin](https://github.com/sndyuk/mangle-css-class-webpack-plugin), but they don't play nicely with the pug+`HtmlWebpackPlugin` setup. Additionally, it doesn't have all the features I would like to have</sup>

### CODE REVIEW

**Comment by ericcornelissen** [comment]
As of 9e97a679e15caeb55592b55cb2c6f7fb95b8a508 the gains of this PR are as per the table below. Not _amazing_, but not bad either 🙂 This includes CSS class mangling and ID mangling.

| File | Size (in `KB`), no mangling | Size (in `KB`), with mangling | Size reduction |
| --- | --- | --- | ---: |
| `index.html` | `3558` | `3246` | `-8.79%` |
| `app.css` | `14` | `12` | `-11.15%` |
| `script.js` | `5` | `5` | `-5.66%` |
| _combined_ | `3567` | `3263` | `-8.80%` |


<details>
<summary>Exact values</summary>

index.html
  before: 3.643.338 bytes
  after:  3.323.026 bytes
  gain:   -8.79%

app.css
  before: 13.830 bytes
  after:  12.288 bytes
  gain:   -11.15%

script.js
  before: 4.626 bytes
  after:  4.364 bytes
  gain:   -5.66%

combined
  before: 3.661.794
  after:  3.339.678
  gain:   -8.80%

</details>

**Comment by ericcornelissen** [comment]
As of 7f093e97d82701017575cf9914705c338ad1957e the gains of this PR are as per the table below. Still not _amazing_, but not bad either 🙂 This includes CSS class mangling, CSS variable mangling (**new**), ID mangling, and HTML attribute mangling (**new**).

| File | Size (in `KB`), no mangling | Size (in `KB`), with mangling | Size reduction |
| --- | --- | --- | ---: |
| `index.html` | `3558` | `3225` | `-9.37%` |
| `app.css` | `14` | `9` | `-35.61%` |
| `script.js` | `5` | `5` | `-6.40%` |
| _combined_ | `3567` | `3016` | `-9.46%` |


<details>
<summary>Exact values</summary>

index.html
  before: 3.643.338 bytes
  after:  3.302.124 bytes
  gain:   -9.37%

app.css
  before: 13.830 bytes
  after:  8,905 bytes
  gain:   -35.61%

script.js
  before: 4.626 bytes
  after:  4,330 bytes
  gain:   -6.40%

combined
  before: 3.661.794
  after:  3.315.359
  gain:   -9.46%

</details>

**Comment by ericcornelissen** [comment]
Quick update on this one, the WebMangler I build for this purpose can now automatically calculate the gains we get from using it. E.g. you can find them for 68e6e20af2014e1feeb4edad004e52233da69ecb in [the Build website job log](https://github.com/simple-icons/simple-icons-website/pull/19/checks?check_run_id=1890555873#step:5:53).

**Comment by ericcornelissen** [comment]
I'm investigating some performances issues caused by our need to mangling over 1700 ids :detective: (hence the failed/cancelled CI build)

**Comment by jorgeamadosoria** [comment]
I would prefer refactoring the code for performance gains, since this is going to be pretty surely unmaintainable moving forward (custom code when the original author leaves tend to do that).
Regardless, if @runxel and @mondeja are ok with this, can we merge it, or it's not ready yet?

**Comment by ericcornelissen** [comment]
This is definitely not yet ready to merge, feel free to close this if you prefer

**Comment by jorgeamadosoria** [comment]
> This is definitely not yet ready to merge, feel free to close this if you prefer

As long as you close it when you know you are no longer going to work on it, I'm ok.

**Pull request closed without merging**
