### PR TITLE
added report icon to the main menu

### LINKED ISSUE #95: Add link to report outdated icons
### Kind of issue 

- [X] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

We should make it easier for users to report outdated icons in an effort to keep our collection up-to-date. Based on discussion (see below) we think the link should basically just point to [the Icon update template](https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=icon+outdated&template=icon_update.md) as (a) this reduces the chances (prevents?) of someone creating many issues quickly in an automated way, and (b) while prefilling details such as the brand name is _nice_, it doesn't add to much value to the UX while adding a lot of HTML (at least one element per icon = at least 1900 elements).

### PR DESCRIPTION
**Pull request by jorgeamadosoria**
Added a "Report Icon" link to the menu to open the "Icon Update" template and simplify icon reporting in the main repository.

### CODE REVIEW

**Review by ericcornelissen — COMMENTED** [review]
I don't think "Report icon" is clear enough as it could also mean something like "report an icon that should be removed".

Ultimately, I think we need some kind of redesign to include this (as it will probably need a longer string for clarity), adding it to the header links isn't going to cut it anymore - see also #39, #49, and #58 - do you have any ideas?

**Comment by jorgeamadosoria** [comment]
- #49  I don't care one way or the other. If I was forced to choose, I wouldn't add it. A link to the website repo is not that relevant. The product is the icon library, the website is merely a showcase.
- #58 is superseded by #39. We could close it, even.
- #39 is good, and we should do it. It would also help add the third parties links (there is a ticket for that) and any other links necessary in the future

**Comment by ericcornelissen** [comment]
Could you leave comments with you thoughts for each of these on those particular issues?

The larger point, that brings those issues and this Pull Request together, is that (1) the header needs some work to begin with and (2) throwing more and more links in the header isn't sustainable; the link to the disclaimer (arguably) shouldn't even be there (we put it there for now because it's a very important link). By "do you have any ideas" I meant do you have any ideas on how we could redesign this in a more sustainable way? (_apologies for not being very clear the first time around_ :sweat_smile:)

**Comment by jorgeamadosoria** [comment]
> Could you leave comments with you thoughts for each of these on those particular issues?
> 
> The larger point, that brings those issues and this Pull Request together, is that (1) the header needs some work to begin with and (2) throwing more and more links in the header isn't sustainable; the link to the disclaimer (arguably) shouldn't even be there (we put it there for now because it's a very important link). By "do you have any ideas" I meant do you have any ideas on how we could redesign this in a more sustainable way? (_apologies for not being very clear the first time around_ 😅)

I like this proposal: https://petershaggynoble.github.io/SI-Sandbox/preview/
It needs an about icon to handle more than one Simple Icons link; a Third party icon to contain a dropdown menu for all of the modules, a report menu if you want to give separate links for reporting different things, etc.
Alternatively, just leaving it like that and add an icon for outdated icon reporting.

**Comment by jorgeamadosoria** [comment]
I've added changes to this PR to conform to the changes in #99 . The icon I chose is a placeholder, if anyone has a different option, it's very likely to be better than this one

**Comment by ericcornelissen** [comment]
I personally don't think the chosen icon (see 
[preview](https://user-images.githubusercontent.com/3742559/132106550-00f6fd37-d0b1-4aab-a7f4-60fbb87d5282.png)) clearly conveys where the link is taking you - or even that it is a link at all (though it being next to the other links should make that somewhat clear, it could also just be interpreted as "there's a warning and we choose to put it here").

An alert symbol could mean so many things and, in my experience, is rarely used by itself as a button/link. If I visited the website as a new user, I would have no idea what this button did and I would definitely not expect it to take me to a new GitHub issue page.

I strongly feel like we should "add this because it's nice to have a convenient link on the website to report outdated icons" if there's even the slightest chance (a not-significant group of) people will get confused.

Also, the link should be `https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=icon+outdated&template=icon_update.yml&title=Update%3A+`.

**Comment by ericcornelissen** [comment]
I think this should definitely not be merged with [the current icon](https://user-images.githubusercontent.com/3742559/132106893-e4394c24-0824-4aeb-b75a-ec883ed875d7.png). The current in no way communicates that it will let the user report an outdated icon. From my perspective it just look like an interactive warning, which if clicked will tell you what the warning is.


I have no suggestion for a better icon. I strongly believe we're better off not adding anything in this regard than adding something that is confusing. I think the only suitable solution is to do in text form. Also, we could perhaps start by adding a link like this to the README of the main project as a trail, to see if having something like this actually increases the number of outdated icons reported.

Also the link is incorrect, it should be: `https://github.com/simple-icons/simple-icons/issues/new?labels=icon+outdated&template=icon_update.yml&title=Update%3A+`

**Comment by jorgeamadosoria** [comment]
> I think this should definitely not be merged with [the current icon](https://user-images.githubusercontent.com/3742559/132106893-e4394c24-0824-4aeb-b75a-ec883ed875d7.png). The current in no way communicates that it will let the user report an outdated icon. From my perspective it just look like an interactive warning, which if clicked will tell you what the warning is.
> 
> I have no suggestion for a better icon. I strongly believe we're better off not adding anything in this regard than adding something that is confusing. I think the only suitable solution is to do in text form. Also, we could perhaps start by adding a link like this to the README of the main project as a trail, to see if having something like this actually increases the number of outdated icons reported.
> 
> Also the link is incorrect, it should be: `https://github.com/simple-icons/simple-icons/issues/new?labels=icon+outdated&template=icon_update.yml&title=Update%3A+`

Adding this as text is not an option after changing the menu to icons.
Unless it is added outside the menu, somewhere else. 
A different icon could be a megaphone or a flag. 
Adding the link in the Readme is fine. Not sure if one thing supersedes the other.

If it were up to me, the report outdate icon would be an option for each one of the icons, with a little flag, in the footer of the icon card (from left to right, it would be color div, icon for svg download, icon for colored svg download, icon for pdf download, icon to report outdated).

**Comment by ericcornelissen** [comment]
> Adding this as text is not an option after changing the menu to icons.

Agreed that wasn't my suggestion. If it's text it should go somewhere else (as you suggested), probably somewhere else in the `<header>`. Alternatively, if we implement a sidemenu (that can also house the header links on small screens) we could put it in there.


> A different icon could be a megaphone or a flag.

I don't think either of these, in the header, are good alternatives. I think the flag would be a reasonable candidate if we add it to the cards.

> Adding the link in the Readme is fine. Not sure if one thing supersedes the other.

I would consider it unrelated, neither change depends on the other.


> If it were up to me, the report outdate icon would be an option for each one of the icons, with a little flag, in the footer of the icon card (from left to right, it would be color div, icon for svg download, icon for colored svg download, icon for pdf download, icon to report outdated).

You could give it a try, but I think this would add too much HTML to the site right now. But hey, maybe it turns out it barely adds anything compared to the overall site :upside_down_face: 

I do think this would be more realistic when we have pagination or lazy-loading implemented.

**Comment by jorgeamadosoria** [comment]
> I do think this would be more realistic when we have pagination or lazy-loading implemented.

Isn't lazy loading implemented via HTML attribute already?

**Comment by ericcornelissen** [comment]
I meant lazy loading of the HTML content, not just lazy rendering the SVGs.

**Comment by jorgeamadosoria** [comment]
Closing this PR since we discussed adding the report icon to the card rather than the menu.

**Pull request closed without merging**
