### PR TITLE
Remove JavaScript blurs

### PR DESCRIPTION
**Pull request by ericcornelissen**
Remove the use of `.blur()` to improve a11y, in particular when it comes to resetting the tabindex when clicking the control buttons.

### CODE REVIEW

**Comment by jorgeamadosoria** [comment]
> Remove the use of `.blur()` to improve a11y, in particular when it comes to resetting the tabindex when clicking the control buttons.

explain this one for my benefit, please? I don't know what blur has to do with accessibility.

**Comment by ericcornelissen** [comment]
When you call `.blur()` on a node it removes the focus from that element and resets it to the top of the page - so if you do that upon clicking on the element it fires the event and then resets the focus to the top of the page. The reason this is bad for a11y is because it is annoying for keyboard users who go through the page content primarily by tabbing through focusable elements.

So, currently on the website, if you tab through to say the buttons for the dark/light mode and "press" (using enter or spacebar) one of them than the mode is changed but the focus is back at the top of the page. There's really no reason for this and it's much nicer if the focus stays where it is so that the keyboard user doesn't have to re-orient themselves as well as tab through a bunch of elements they already saw.

**Comment by jorgeamadosoria** [comment]
> When you call `.blur()` on a node it removes the focus from that element and resets it to the top of the page - so if you do that upon clicking on the element it fires the event and then resets the focus to the top of the page. The reason this is bad for a11y is because it is annoying for keyboard users who go through the page content primarily by tabbing through focusable elements.
> 
> So, currently on the website, if you tab through to say the buttons for the dark/light mode and "press" (using enter or spacebar) one of them than the mode is changed but the focus is back at the top of the page. There's really no reason for this and it's much nicer if the focus stays where it is so that the keyboard user doesn't have to re-orient themselves as well as tab through a bunch of elements they already saw.

got it.
So the idea is to keep the focus in the just clicked element to make people able to tab along and not having to restart their navigation.
I have no problem with that.

**Comment by jorgeamadosoria** [comment]
your code looks fine and to the point. IMO you can merge.

**Comment by ericcornelissen** [comment]
> So the idea is to keep the focus in the just clicked element to make people able to tab along and not having to restart their navigation.

Correct


> your code looks fine and to the point. IMO you can merge.

Did you give a try locally, nothing buggy happens when you interact with the page on your end?

**Comment by jorgeamadosoria** [comment]
yes, I tested it locally, I don't see a problem. 
The tabbing order (except the known issue when ordering by color) is fine.
I searched, chose the different orderings, and color schemes, downloaded a file, etc. At least it's not buggy, that's certain

**Comment by ericcornelissen** [comment]
Thanks @jorgeamadosoria, merged it in now :ok_hand:

**Pull request merged**
