### PR TITLE
Use Node.js 16

### PR DESCRIPTION
**Pull request by LitoMore**
~~Consistent with the Node.js version in Docker.~~

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Any particular reason you closed this @LitoMore? Depending on the outcome of https://github.com/simple-icons/simple-icons/pull/6179 I do think we want to merge this Pull Request.

**Comment by LitoMore** [comment]
You have solved my concerns!

Let's go for it!

**Comment by LitoMore** [comment]
@ericcornelissen Do we need to drop lockfile for this repo?

**Comment by ericcornelissen** [comment]
I think that the dependencies in this project (as well as [font](https://github.com/simple-icons/simple-icons-font), [release-action](https://github.com/simple-icons/release-action), and probably [pdfs](https://github.com/simple-icons/simple-icons-pdf)) are a bit more "advanced" than the dependencies of the main project and I don't think it's a good idea to just drop the `package-lock.json` here because of that. Not to mention that the "problem" is much less severe here due to there being less activity.

That's not to say we shouldn't do anything in this (or any of the other projects). If you don't mind, should we use #103 and #104 instead to resolve the discussion?

**Comment by LitoMore** [comment]
Agree.

**Pull request closed without merging**
