### PR TITLE
Add link to DISCLAIMER.md

### LINKED ISSUE #58: Consider design for link to DISCLAIMER.md
### Kind of issue 

- [ ] Feature
- [ ] Bug
- [x] Design
- [ ] Other, namely: _requirement_

### Description

~~Add a link to the `DISCLAIMER.md` of the project - depends on https://github.com/simple-icons/simple-icons/pull/4912.~~

In #74 we were not necessarily happy about the design aspect of the link to the disclaimer, but we merged it in in the interest of having some link while we figure out the design. This ticket now serves to keep this topic alive and potentially discuss the design of the link to the disclaimer.

### PR DESCRIPTION
**Pull request by adamrusted**
This PR adds a link to the current (develop) version of the DISCLAIMER.md file.
My other thoughts would be to link to the `master` branch, so that the disclaimer people read has passed at least one release window - or to generate a page on the website based on the markdown file itself.

### CODE REVIEW

**Comment by ericcornelissen** [comment]
I would be okay with this but I'm wondering if we can put it in another place - putting it in _that_ list of links doesn't feel quite right to me. Do you want to play around with some other options? E.g. between the controls and the start of the grid or somewhere around the "X Free SVG icons for popular brands" message?


> This PR adds a link to the current (develop) version of the DISCLAIMER.md file.
> My other thoughts would be to link to the master branch, so that the disclaimer people read has passed at least one release window

I think it should link to the version on the `master` branch.


> or to generate a page on the website based on the markdown file itself.

That could be cool in the long run, but I think linking to it is a good first step.

**Comment by adamrusted** [comment]
So I've tried a few variants, styling is obviously subject to some additional work.
- [In the Main Menu](https://user-images.githubusercontent.com/1830867/120113220-6da61c00-c171-11eb-826f-501a5c774ea5.png)
- [Under `X free SVG icons`](https://user-images.githubusercontent.com/1830867/120113241-7b5ba180-c171-11eb-81f6-f308ca52dec4.png)
- [Below the control bar, before the icon grid](https://user-images.githubusercontent.com/1830867/120113265-94645280-c171-11eb-8539-6ce88cc85580.png)

I think I prefer the last option - though I'd prefer to see it as a proper banner.

**Comment by ericcornelissen** [comment]
Considering that we probably want to move away from the "large" header, something along the lines of [the last option](https://user-images.githubusercontent.com/1830867/120113265-94645280-c171-11eb-8539-6ce88cc85580.png) is probably the way to go. Any other thoughts on this @simple-icons/maintainers?

**Comment by PeterShaggyNoble** [comment]
Given its importance, should we look into trying to position it somewhere near the search form so we can make it `sticky`? If not then including in the menu as it currently is in the PR makes most sense to me with option 2 being a close second for me.

**Comment by ericcornelissen** [comment]
> Given its importance, should we look into trying to position it somewhere near the search form so we can make it sticky?

I'd personally not be a fan of making this sticky, or at least using any additional vertical sticky space.


> including in the menu as it currently is in the PR makes most sense to me with option 2 being a close second for me.

I think I agree, we can always update this later.

**Comment by ericcornelissen** [comment]
In the interest of having _some_ link to the disclaimer on the website I'll be merging this in now. But, I'll immediately reopen the related issue with an updated title to keep this topic alive 🙂

**Pull request merged**
