### PR TITLE
Added Ukrainian locale

### PR DESCRIPTION
**Pull request by Andygol**
I bring to your attention PR, which adds Ukrainian locale.

### CODE REVIEW

**Comment by adamrusted** [comment]
Thanks so much for your contribution @Andygol - and don't worry about the tests failing. We'll get to looking at that, looks like an issue on our end. Would you be so kind as to contribute the locale to the _beta_ website repo too, over at https://github.com/mondeja/simple-icons-website-rs?

**Comment by Andygol** [comment]
image
I've tested locally and all looks good.


> Would you be so kind as to contribute the locale to the beta website repo too, over at https://github.com/mondeja/simple-icons-website-rs?

Sure, I'll take a look.

**Comment by Andygol** [comment]
@adamrusted look here https://github.com/mondeja/simple-icons-website-rs/pull/117

**Review by mondeja — APPROVED** [review]
Looks good. Thank you! 🇺🇦

**Pull request merged**
