### PR TITLE
Issue 101- lowercased npm in the nav bar

### LINKED ISSUE #101: npm Should always be lowercase (top nav)
### Kind of issue 

* [x] Bug

### Description

npm the company/product/cli is always lowercase, `npm`, never uppercase, `NPM`.

* https://www.npmjs.com/about
* https://twitter.com/seldo/status/850042251635867648 - Co-founder of npm

### PR DESCRIPTION
**Pull request by dylvaz**
#101 wanted npm to be lowercased

### CODE REVIEW

**Review by ericcornelissen — CHANGES_REQUESTED** [review]
Thanks for the quick action! Could you look into reverting the changes to the `package-lock.json` file? If you're unsure how to fix that I can take care of it before merging.

**Comment by dylvaz** [comment]
Yeah I can work on reverting the changes.

**Comment by dylvaz** [comment]
image

Looks like changing the text from 'NPM' to 'npm' caused the e2e test to fail. I'm going to go ahead and fix that in e2e.test.js

**Review by ericcornelissen — APPROVED** [review]

**Comment by ericcornelissen** [comment]
Thank you very much for jumping in and fixing this issue so quickly @dylvaz! :confetti_ball:

**Comment by dylvaz** [comment]
Thank you @ericcornelissen ! I look forward to contributing more.

**Pull request merged**
